warning: function is never used: `sha256`
  --> src/lib.rs:31:4
   |
31 | fn sha256(path: &str) -> Result<String, std::io::Error> {
   |    ^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running target/debug/deps/fhc-ff245847c9dfa3ac

running 3 tests
test tests::empty ... ok
test tests::good ... ok
test tests::file_does_not_exist ... FAILED

failures:

---- tests::file_does_not_exist stdout ----
thread 'tests::file_does_not_exist' panicked at 'assertion failed: match sha256("tests/none.txt") {
    Err(ref e) => e.kind() == std::io::ErrorKind::NotFound,
    _ => false,
}', src/lib.rs:21:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    tests::file_does_not_exist

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
